### ISSUE TITLE
可以给我一个86duino的xp系统sd卡img备份吗？yangkkokk@163.com yangkkokk@gmail.com

### ISSUE THREAD

**Issue by yangkkokk** [Sayter99/86ME#1]
可以给我一个86duino的xp系统sd卡img备份吗？yangkkokk@163.com yangkkokk@gmail.com

**Comment by Sayter99** [comment]
很抱歉我們沒有 XP 作業系統的 image，建議你可以自行安裝 XP 到 86Duino 上。還有此問題與 86ME 並無關聯，我會關閉這個 issue，謝謝。
